apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-bbdd-vol1
spec:
  storageClassName: bbdd
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/bbdd-vol1"
